### ISSUE TITLE
slash command fail

### ISSUE THREAD

**Issue by tgly307** [scottleedavis/mattermost-plugin-spybot#5]
hi, thanks for this plugin.
I install the release package version 0.1.2, the command /spy and /unspy can not trigger the bot, and I tried version 0.1.1, it works.

**Comment by scottleedavis** [comment]
Hi @tgly307 I verified running 0.1.2 on debian stretch, mattermost server 5.10.0.

Could you let me know what server/system you are running on?  Could you share logs?

Also, could you try disable/enable the 0.1.2 bot?

**Comment by tgly307** [comment]
Hi. I tried reinstall the plugin 0.1.2 after 0.1.1 and it works. Maybe disable/enable the plugin will make it work too. Thanks for reminding me.
I will close this issue.
