### ISSUE TITLE
Not working on MM 5.10

### ISSUE THREAD

**Issue by uhlhosting** [scottleedavis/mattermost-plugin-spybot#6]
`2019-05-15T09:38:06.612+0200	error	mlog/log.go:172	RPC call OnConfigurationChange to plugin failed.	{"plugin_id": "com.github.scottleedavis.mattermost-plugin-spybot", "error": "connection is shut down"}
`

**Comment by scottleedavis** [comment]
Hi @uhlhosting , could you please try the latest release?  I reduced what that function does and added better error checking.  https://github.com/scottleedavis/mattermost-plugin-spybot/releases/tag/v0.1.3

**Comment by tgly307** [comment]
@scottleedavis I tried v0.1.3, but it not work on MM 5.10 and there is no error log .
v0.1.2 is work fine for me.

**Comment by scottleedavis** [comment]
@uhlhosting does 0.1.2 or 0.1.3 work for you on 5.10?

**Comment by scottleedavis** [comment]
@tgly307 When you say not working, the plugin refuses to enable?  `/spy` doesn't work or... ?

**Comment by uhlhosting** [comment]
@scottleedavis I managed to run once a /spy on a username, got no reply from nothing, how does in action should work?

**Comment by tgly307** [comment]
@scottleedavis when I use command /spy @someone, I got nothing response. when someone online, the bot does not send a message to me.

**Comment by scottleedavis** [comment]
@uhlhosting yes that is the bug that I believe is now fixed.  There will be an ephemeral message after `/spy @user` that says `spying on user @user`

@tgly307 Thank you!  I was able to replicate and focus on the bug with that info too.

Could you both try the latest version?  I believe it solves the issues.  Tested on 5.10.
https://github.com/scottleedavis/mattermost-plugin-spybot/releases/tag/v0.1.4

**Comment by tgly307** [comment]
@scottleedavis The plugin v0.1.4 works fine on MM 5.11. Thanks for quick fixing

**Comment by scottleedavis** [comment]
sounds like the plugin is working @uhlhosting .  Please reopen the issue if you find the latest version does not work for you.  (try 0.1.5 with `/spy list` ! ).  closing
