### ISSUE TITLE
feature wanted: Add spy user list

### ISSUE THREAD

**Issue by tgly307** [scottleedavis/mattermost-plugin-spybot#7]
When I add several users in spy list, I want to know how many or who in the list. I think it would be great to add a feature `/spy list` that can list all users in my list.

**Comment by scottleedavis** [comment]
Will do!

**Comment by scottleedavis** [comment]
Done @tgly307 !  Let me know if there are other requests.  :)
https://github.com/scottleedavis/mattermost-plugin-spybot/releases/tag/v0.1.5
