### ISSUE TITLE
command /unspy remove all users in spy list

### ISSUE THREAD

**Issue by tgly307** [scottleedavis/mattermost-plugin-spybot#8]
I installed the newest version plugin to test command `/spy list`, thanks for the quick release. And I found command `/unspy `remove all users in spy list instead of the designated one.
Here is my testing process:
![image](https://user-images.githubusercontent.com/25153311/57965466-3643e880-7977-11e9-8bec-09bcad582a1b.png)

```
1. /spy list (empty)
2. /spy @freemagico_bot (spy one user)
3. /spy list (the list has one user)
4. /spy @github (spy another user)
5. /spy list (the list has two users)
6. /unspy @github (remove @github from the list)
7. /spy list (the list is empty, @freemagico_bot is gone)
```
 Then I change the online state of `@freemagico_bot`, the spybot not send message to me, obviously the user is not in the list now.

**Comment by scottleedavis** [comment]
@tgly307 v0.1.6 release should solve this issue.  :)

https://github.com/scottleedavis/mattermost-plugin-spybot/releases/tag/v0.1.6

**Comment by scottleedavis** [comment]
please reopen if you find otherwise!  :)

**Comment by tgly307** [comment]
@scottleedavis it works fine, thx!
